---
# title: "Generic Manuscript Template"

# This sets up the format to match most journal requirements of 1" margins
# and 12pt Times new Roman font. The catch is that to specify the font
# you have to use xelatex latex_engine. Also important to note, most journals 
# need Word files (or Latex) for copy editing.
geometry: margin=1in
header-includes:
    - \usepackage{setspace}
    - \doublespacing
    - \usepackage{lineno}
    - \linenumbers
    - \usepackage{fontspec}         # can only be used with xelatex output
    - \setmainfont{Times New Roman} # can only be used with xelatex output

output: 
  pdf_document:
    latex_engine: xelatex
## Other output options are:
# output: pdf_document
# output: html_document
# output: word_document

## Specify your csl here. You can use local or remote (local is better)
# csl: https://raw.githubusercontent.com/citation-style-language/styles/master/ecology-letters.csl
csl: https://www.zotero.org/styles/ecology-letters
# csl: "ecology-letters.csl"
bibliography: references.bib
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Title**: The title of your groundbreaking research paper

First Author^1^\*, Second Author^1^, Third Author^2,1^

1.  Dept. of Biology, Institution A, City, Province, Country

2.  Environmental Science Centre, Governmental Organisation, City, Province, Country

\*Corresponding Author

email: first.author\@institutiona.ca (FA)

**Author Contributions:** FA conceived of the study, conducted the analyses, and wrote the original, and revised drafts of the manuscript. SA, and TA, helped with the draft manuscript and revisions and supplied guidance to FA. TA provided the data for the case study, contributed to the revisions, and assisted with the analysis of the case study data.

**Data Availability:** The data and code that support the findings of this study are openly available on Zenodo / GitHub at <https://link_to_archived_release_or_GitHub.com>.

**Conflict of Interest statement**

No conflicts of interest

**Acknowledgements:** We would like to thank a whole bunch of people.

\newpage

# Abstract

1.  Ecologists often have lots of questions about lots of stuff

2.  We evaluated a bunch of things using sophisticated methods and carried out complicated statistical tests

3.  We discovered a bunch of things that we didn't already know but suspected

4.  Our research has greatly advanced out knowledge about stuff and will make a significant contribution to something and someone

**Key-words**: stuff, something

\newpage

# Introduction

Ecologists have long recognized that some combinations of species are regularly found together, while other combinations occur infrequently [@Cole:1949dz; @Elton:1946dl].

# Methods

To evaluate the ...

As with Pielou's Evenness [@Pielou:1967ea], Shannon's diversity index [@Shannon:1948iy]$(H)$ is normally calculated from species abundance values; however, for our purposes it is calculated from the column totals (species richness per sample) using the following equation:

$$
H_x = -S[P(i_x) \times ln(P(i_x))]
$$

where $x$ denotes which set of values we are using to calculate the index (observed, minimal or maximal), and $P(i_x)$ is the proportion of species that occur in each sample $(i)$.

Statistical analyses were carried out in R 3.4.0 (R Core Team 2017). All code along with the simulation algorithms used are available on Zenodo / GitHub <https://link_to_archived_release_or_GitHub.com>.

# Results

# Discussion

# References

::: {#refs}
:::

\newpage

# Tables

\newpage

# Figure Captions

**Figure 1**.

**Figure 2**.

\newpage

# Figures

Figure 1.

\newpage

Figure 2.

\newpage

# Appendices
